# In mac:
# command: ansible-playbook print-vault-secret.yml -vvvv

# if you are getting this error: ERROR! A worker was found in a dead state 
# then try:
# export OBJC_DISABLE_INITIALIZE_FORK_SAFETY=yes
# export no_proxy="*"
# env no_proxy='*' sudo ansible-playbook print-vault-secret.yml -vvvv 

# Refer: 
# https://groups.google.com/g/ansible-project/c/67mEWh4cUts
# https://github.com/ansible/ansible/issues/32554

- name: (Playbook) "Getting Vault Secrets"
  hosts: localhost
  connection: local
  tasks:
  - name: Return rabbitmq secret from a path
    debug:
      msg: "{{ lookup('hashi_vault', 'secret=secret/data/rabbitmq token=root url=http://localhost:8200')}}"

- name: (Playbook) "Getting Vault Secrets"
  hosts: localhost
  connection: local
  tasks:
  - name: Return rabbitmq secret from a path
    debug:
      msg: "{{ lookup('hashi_vault', 'secret=secret/data/rabbitmq:data token=root url=http://localhost:8200')}}"

- name: (Playbook) "Getting Vault Secrets"
  hosts: localhost
  connection: local
  tasks:
  - name: Return rabbitmq secret from a path
    set_fact:
      result: "{{ lookup('hashi_vault', 'secret=secret/data/rabbitmq:data token=root url=http://localhost:8200')}}"

- name: (Playbook) "Getting Vault Secrets"
  hosts: localhost
  connection: local
  tasks:
  - name: debug fact
    debug:
      msg: "{{ result.password }}"