# Refer: https://github.com/bitnami/charts/blob/master/bitnami/rabbitmq/values.yaml

## RabbitMQ Authentication parameters
##
auth:
  ## RabbitMQ application username
  ## ref: https://github.com/bitnami/bitnami-docker-rabbitmq#environment-variables
  ##
  username: user

  ## RabbitMQ application password
  ## ref: https://github.com/bitnami/bitnami-docker-rabbitmq#environment-variables
  ##
  password: testing
  # existingPasswordSecret: name-of-existing-secret